language: node_js
node_js:
 - "stable"
# cache:
#   directories:
#     - "node_modules"
script:
  - npm install -g
#   - npm test #Runs Tests
  - npm run deploy
#
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $githubToken
#   local_dir: build
#   on:
#     branch: master
